fruits=[]
First=input("Enter first fruit of your choice:")
fruits.append(First)
sec=input("Enter first fruit of your choice:")
fruits.append(sec)
third=input("Enter first fruit of your choice:")
fruits.append(third)
fourth=input("Enter first fruit of your choice:")
fruits.append(fourth)
fifth=input("Enter first fruit of your choice:")
fruits.append(fifth)
sixth=input("Enter first fruit of your choice:")
fruits.append(sixth)
seventh=input("Enter first fruit of your choice:")
fruits.append(seventh)
print(fruits)