num1=input("Enter num1")
num2=input("Enter num2")
num3=input("Enter num3")
num4=input("Enter num4")
num5=input("Enter num5")
num6=input("Enter num6")
num7=input("Enter num7")
num8=input("Enter num8")
num1=int(num1)
num2=int(num2)
num3=int(num3)
num4=int(num4)
num5=int(num5)
num6=int(num6)
num7=int(num7)
num8=int(num8)
s=set()
s.add(num1)
s.add(num2)
s.add(num3)
s.add(num4)
s.add(num5)
s.add(num6)
s.add(num7)
s.add(num8)
print(s)


